travis:
  secure:
    BINSTAR_TOKEN: Ak9/oUl9TqBQSciyq3muXG943jsunp6GzCn5mkWM4QxrwPyqibQ2IA9GL/MftkFK1yC83UyXVqvAiMswlWLnSp0ioNJhd+RsUu6Ol16PnzhQcApXmcTMVpf+hqaXN5C0E0A1lGodX4GKd33cdZ+RfZzNMjbq6nfUbn09SaIt7wXVO32+WpCCjU2fJcTR4pOAGi3kSFxPMoqhx7QyfGk6VMhLX8wvEpwAsXwWMh8JqzzQBA9e8dILj0XyO9bKtVesD1oUmxAy5NyL7nuxF4RItLZpuJp2215rGnxxeg+xy8ksdeIfaN2HEG5WH4bJmOCOsDcPK30mIJ0lz0U9xrd1YKH90tqkpFgMZd83zVc+/T2ljYsy2cF2se3UnhGsGm5PUpovANOG0Gp6sLRYitXSe6iKwLiMUjL3FoiLCRHMLMMWMdPFSuzCalhYj4odZV6kVSAr/SOkaRTw11NS+wm7cBSjij5sE0tGwkM6Dm8QHjc12UN5ZdR7DUgu2jM+Ef95Hwccb2MAN9O0ug3I5+0UugFgycb+cnAVpKw9dX0UgEwg57ivXdNnsAR0ZJzk5Wr32Azw80iofslj/4eiNnLCPVFPRIHfm6o+I9FTADsmAo+ljyU2Mg7COrwPT/ufeYrffCmg/N83HmTbOO63tTFjW6AX/Zi5hWeCw7EFlvuthAI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
